### ISSUE TITLE
ImportError: No module named 'icu'

### ISSUE THREAD

**Issue by Fiedzia** [aboSamoor/polyglot#10]
python3.4:
pip install polyglot
from polyglot.text import Text, Word
---> 11 from icu import Locale
     12 import pycld2 as cld2
     13 

ImportError: No module named 'icu'

Its not a module dependency nor is it mentioned in readme.

**Comment by aboSamoor** [comment]
Please follow the installation instrcutions mentioned in the documentation

http://polyglot.readthedocs.org/en/latest/Installation.html

**Comment by davidvartanian** [comment]
Fiedzia is right. The error refers to a Python module, but libicu-dev is a Linux dependency (you need both).
I've got rid of this error installing the package _python3-icu_.
Then another dependency error ocurred:
ImportError: No module named 'pycld2' (yes, I'd followed the installation instructions too).
Then I installed _pycld2_ with pip3 and everything went well.

**Comment by peide** [comment]
Anaconda default icu's version is 54. There are problems when building pyicu with these libraries.
Update ICU to version 58:
conda install -c conda-forge icu=58.1

**Comment by lukaskawerau** [comment]
Is this getting fixed? I'm trying to use polyglot with Anaconda and Python 3.5 and get the same error as above. The suggestions for installing python3-icu, pycld2 and icu=58.1 do not resolve the problem.

**Comment by mwozniczak** [comment]
@lukaskawerau try `pip install pyicu`

**Comment by Mika15** [comment]
Guys, I got the same issue. I found this great article and the problem was resolved: https://tobywf.com/2017/05/installing-pyicu-on-macos/

**Comment by davidvartanian** [comment]
pyICU can be quite tricky because it should be installed to use a particular version of ICU, and this depends on each operating system. Incompatibility problems like the famous "undefined symbol" are, as I understand, related to the difference of versions between the operating system and the python library.
In addition, Anaconda makes things easier but there's an exception with these libraries.
This is my comment about Anaconda's installation but actually the same thing: https://github.com/aboSamoor/polyglot/issues/78#issuecomment-302667102

**Comment by olmerg** [comment]
for me work
`pip3 install pyicu`
`pip3 install pycld2`

**Comment by sjlongland** [comment]
@aboSamoor I have `icu` installed (Gentoo system; so libraries *and* headers) and struck the same issue as others.  It appears `icu` (aka `libicu` on Debian) is not the package that provides the `icu` module in Python; `pyicu` is.

`emerge dev-python/pyicu` followed by `pip3 install --user pycld2 morfessor` (since the latter two aren't in Gentoo repositories), cured the issue for me.  I think `pyicu` would be worth mentioning in your documents, as it seems *it*, not `icu` itself, is the direct dependency.

Directing people at a document that clearly references the wrong dependency does not help. :-)

**Comment by simonfullernuim** [comment]
Hi, on py2.7.12 ubuntu 16.04 I get the following error from `polyglot.detect import Detector`:
`ImportError: libicule.so.54: cannot open shared object file: No such file or directory`
I have already tried `conda install -c conda-forge icu=58.1` and reinstalling but this does not help.
Do you have any suggestions to solve this particular problem?
Otherwise could you suggest another workaround to get the language detector functionality?
Thanks!

**Comment by tigerninjaman** [comment]
What worked for me was downloading the polyglot master file as well as the correct pycld2 and pyicu .whl files from [https://www.lfd.uci.edu/~gohlke/pythonlibs/](here), then doing pip install pycld2-0. ... .whl and pip install pyicu- ... .whl, then navigating inside polyglot-master and doing python setup.py install.

**Comment by suhailgupta03** [comment]
> @lukaskawerau try `pip install pyicu`

It is still not working for me. `pip install pyicu` only works with `sudo` and I have installed everything but still see this error.

**Comment by npow** [comment]
I got it to work on anaconda with `conda install -c conda-forge pyicu`

**Comment by christofs** [comment]
Installing ```pyicu``` also worked for me. It would have helped a lot if the dependency mentioned in the error message would have been ```pyicu``` rather than just ```icu```. (Also, this dependency should of course have been installed when I installed polyglot in the first place.)

**Comment by josircg** [comment]
If you are running on Debian/Ubuntu and using python3, try:

`pip install PyICU`

**Comment by eduamf** [comment]
```
sudo apt-get install build-essential
pip install PyICU
```

**Comment by jonathan-kosgei** [comment]
I had to do the following to get it to work;

```
python3.7 -m pip install polyglot
sudo apt-get install python3.7-numpy libicu-dev
sudo apt-get install python3.7-icu
python3.7 -m pip install morfessor
```

**Comment by Infovarius** [comment]
> Please follow the installation instrcutions mentioned in the documentation
> 
> http://polyglot.readthedocs.org/en/latest/Installation.html

It doesn't help. ICU can't be installed: KeyError: 'ICU_VERSION'

**Comment by Infovarius** [comment]
> If you are running on Debian/Ubuntu and using python3, try:
> 
> `pip install PyICU`

RuntimeError:
    Please set the ICU_VERSION environment variable to the version of
    ICU you have installed.

**Comment by donglixp** [comment]
```
conda install -c conda-forge pyicu 
```

**Comment by agn-7** [comment]
In my case, the following packages needed:

```
pip install pyicu 
pip install pycld2
pip install morfessor
```

**Comment by Chromanon** [comment]
> I had to do the following to get it to work;
> 
> ```
> python3.7 -m pip install polyglot
> sudo apt-get install python3.7-numpy libicu-dev
> sudo apt-get install python3.7-icu
> python3.7 -m pip install morfessor
> ```

Thank you! it has worked for me

**Comment by j127** [comment]
In case this can help anyone save a few hours of frustration, I wrote [a quick tutorial](https://forum.codeselfstudy.com/t/how-to-install-and-run-the-polyglot-package-python-in-docker/2031) on how I got it running in Docker.

**Comment by ojomio** [comment]
Why won't anyone add it to the requirements?

**Comment by YeChaopeng** [comment]
在linux环境安装polyglot：
1. 更新setuptools：pip3 install -U setuptools
2. 安装polyglot：pip3 install polyglot -i https://mirrors.aliyun.com/pypi/simple
3. 安装libicu-dev：sudo apt-get install python-numpy libicu-dev
4. 安装pyicu：pip3 install pyicu -i https://mirrors.aliyun.com/pypi/simple
5. 安装pycld2：pip3 install pycld2 -i https://mirrors.aliyun.com/pypi/simple
6. 安装morfessor：pip3 install morfessor -i https://mirrors.aliyun.com/pypi/simple

**Comment by rbkahn** [comment]
conda install -c conda-forge pyicu was the thing I needed to get past the icu step.

**Comment by Atul-Anand-Jha** [comment]
There's a simple hack to tackle this problem. -> Downgrade your pyicu version.
pyicu V2.3.1 worked for me, and i believe it will also work for most of you.

try this: 
`
pip install polyglot
sudo apt-get install python-numpy libicu-dev
pip install pyicu==2.3.1
pip install morfessor
`
It definitely worked for me.

**Comment by 13muskanp** [comment]
pip3 install -U git+https://github.com/aboSamoor/polyglot.git@master
This one worked out well for me

**Comment by aakashkag** [comment]
@13muskanp your solution worked without facing any further issue. saved my day. thank you.

**Comment by renorosgon** [comment]
Hello!

I stil get the same error

`ImportError: cannot import name 'Locale' from 'icu'`

I'm on Linux Manjaro so I wanted to know the equivalent for `libicu-dev`

**Comment by Atul-Anand-Jha** [comment]
> Hello!
> 
> I stil get the same error
> 
> `ImportError: cannot import name 'Locale' from 'icu'`
> 
> I'm on Linux Manjaro so I wanted to know the equivalent for `libicu-dev`

try the above hack which i have mentioned. that worked for me on several virtual envs.

**Comment by 0x4f53** [comment]
> Hello!
> 
> I stil get the same error
> 
> `ImportError: cannot import name 'Locale' from 'icu'`
> 
> I'm on Linux Manjaro so I wanted to know the equivalent for `libicu-dev`

Make sure PyICU is installed in the correct location. I accidentally installed it via sudo and it took me a lot of time to fix.

First, remove any traces of ICU with `sudo pip uninstall pyicu` and `pip uninstall pyicu`
If you want to download whatever's latest, clear pip's cache via `pip cache purge`
Then reinstall it with `pip install pyicu`.

**Comment by aalok-sathe** [comment]
> Hello!
  I stil get the same error
  ImportError: cannot import name 'Locale' from 'icu'
  I'm on Linux Manjaro so I wanted to know the equivalent for libicu-dev

@renorosgon 
On RHEL I installed `libicu-devel`, there is likely a package with a similar name for your distribution.

**Comment by xihajun** [comment]
This code below works on Google Colab
```
!pip install polyglot

!sudo apt-get install python-numpy libicu-dev

!pip install pyicu==2.3.1

!pip install morfessor

!pip install pycld2
```

**Comment by DerXter** [comment]
If you have a Mac M1 or higher, you may need a few more steps before those presented by @Mika15. 
You can take a look at the full process on this [StackOverflow response](https://stackoverflow.com/questions/64886067/polyglot-importerror-cannot-import-name-locale-from-icu/74986011#74986011).

**Comment by AgaMiko** [comment]
For me installing [those](https://github.com/aboSamoor/polyglot/blob/master/rtd_requirements.txt) requirements helped:
```wheel>=0.23.0
pycld2>=0.20
six>=1.7.3
futures>=2.1.6
sphinxcontrib-napoleon>=0.2.8
mock>=1.0.1
sphinx-bootstrap-theme>=0.4.5
alabaster>=0.7.1```

**Comment by ronyarmon** [comment]
Coming back to polyglot after a while and reading here and in other source following some installation errors I propose the following for Ubuntu (22.04.2 LTS):
**Ubuntu/Linux packages**
`$ sudo apt-get install libicu-de pkg-config`
**Python libraries**
'pip install polyglot pycld2 PyICU morfessor`

**Comment by elephantasticio** [comment]
> sudo apt-get install libicu-de pkg-config

small typo, should read:
```sudo apt-get install libicu-dev pkg-config```

**Comment by KonstantinosSekaras** [comment]
To also note in case anyone has additional issues, you need to have `python3-dev` installed:
`apt-get install python3-dev`
