### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by iamtrask** [aboSamoor/polyglot#11]
This is using 
"pip install polyglot".

I've located some useful arguments that can help here, but I'm not sure how to add them to the cc command.

Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/k1/6_4k217j1ng5qnm8_vrpx1b80000gp/T/pip-build-uOkJfF/PyICU/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/k1/6_4k217j1ng5qnm8_vrpx1b80000gp/T/pip-EdbjO8-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.10-intel-2.7
    copying icu.py -> build/lib.macosx-10.10-intel-2.7
    copying PyICU.py -> build/lib.macosx-10.10-intel-2.7
    copying docs.py -> build/lib.macosx-10.10-intel-2.7
    running build_ext
    building '_icu' extension
    creating build/temp.macosx-10.10-intel-2.7
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/usr/local/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _icu.cpp -o build/temp.macosx-10.10-intel-2.7/_icu.o -DPYICU_VER="1.9.2"
    In file included from _icu.cpp:27:
    ./common.h:86:10: fatal error: 'unicode/utypes.h' file not found
    #include <unicode/utypes.h>
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

**Comment by aboSamoor** [comment]
You can refer to the installation instructions over here
http://polyglot.readthedocs.org/en/latest/Installation.html

Basically, you need to install 
```bash

sudo apt-get install python-numpy libicu-dev
```

**Comment by valeriocos** [comment]
Hi, I had some problems installing Polyglot on my Windows machine (I did not find any information for Windows distributions at http://polyglot.readthedocs.org/en/latest/Installation.html).

I was able to make it run by downloading the following Windows Binaries from ```http://www.lfd.uci.edu/~gohlke/pythonlibs/``` 
- ```NumPy```
- ```PyICU```
- ```PyCLD2```

and installing them through the command line 
```pip install <name_of_the_binary>.whl```

**Comment by dchaplinsky** [comment]
I'd recommend to add this to the installation guide.
https://github.com/Homebrew/homebrew/issues/34170#issuecomment-63192387

It helped me to install polyglot on my mac.

**Comment by winterismute** [comment]
Hi there, I am having also issues installing polyglot on Win10, python3.4 64bit. I have installed nunpy, PyICU  and pycld2 from the website above. However, when trying
    pip install polyglot
I still get:

```bash
  Downloading polyglot-16.7.4.tar.gz (126kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Rudi\AppData\Local\Temp\pip-build-3alcyvz3\polyglot\setup.py", line 15, in <module>
        readme = readme_file.read()
      File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4941: character maps to <undefined>
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Rudi\AppData\Local\Temp\pip-build-3alcyvz3\polyglot\
```

Anybody who can help?

**Comment by Siz001** [comment]
Collecting polyglot
  Using cached polyglot-16.7.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\s1142269\AppData\Local\Temp\pip-build-7mgngns7\polyglot\setup.py", line 15, in <module>
        readme = readme_file.read()
      File "C:\Users\s1142269\AppData\Local\Continuum\Anaconda3-64\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4941: character maps to <undefined>
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\s1142269\AppData\Local\Temp\pip-build-7mgngns7\polyglot\

**Comment by alexgarel** [comment]
Hi this is a problem with anaconda, not polyglot.

Anaconda seems to try to default to cp1252 character encoding instead of the standard UTF-8 encoding.

https://docs.continuum.io/ae-notebooks/install/release#v0-7-0-june-12-2015 tells that it should use UTF-8 encoding, but you may have tweaked it ?

**Comment by winterismute** [comment]
Hi @alexgarel , thank you for your answer. Actually, I did not have Anaconda installed, only a bare-bones python3.4 installation on Win. However, after having installed the prerequisites as I have said, I did manage to install polyglot by downloading the package and calling setup.py. Maybe it's something helpful to know for future development?
Thank you again for the reply.

**Comment by nabti** [comment]
HI, 
I had the same problem to install polyglot on windows. To resolve this I had to do (on anaconda): 
- install PyICU.whl   from https://www.lfd.uci.edu/~gohlke/pythonlibs/
- install PyCLD2.whl   from https://www.lfd.uci.edu/~gohlke/pythonlibs/
- git clone https://github.com/aboSamoor/polyglot
- cd polyglot
- python setup.py install

hope that helps

**Comment by kniveditha** [comment]
For Windows 8

After installing PyICU.whl and PyCLD2.whl, I tried
`pip install -U git+https://github.com/aboSamoor/polyglot.git@master`

I get an error saying 'Futures python package requires python >= 2.6' and I'm using Python 3.7

```
+https://github.com/aboSamoor/polyglot.git@master
Collecting git+https://github.com/aboSamoor/polyglot.git@master
  Cloning https://github.com/aboSamoor/polyglot.git (to revision master) to c:\u
sers\user\appdata\local\temp\pip-req-build-v301wqo4
Requirement already satisfied, skipping upgrade: wheel>=0.23.0 in c:\users\user\
appdata\local\programs\python\python37\lib\site-packages\wheel-0.33.0-py3.7.egg
(from polyglot==16.7.4) (0.33.0)
Requirement already satisfied, skipping upgrade: PyICU>=1.8 in c:\users\user\app
data\local\programs\python\python37\lib\site-packages (from polyglot==16.7.4) (2
.2)
Requirement already satisfied, skipping upgrade: futures>=2.1.6 in c:\users\user
\appdata\local\programs\python\python37\lib\site-packages\futures-3.2.0-py3.7.eg
g (from polyglot==16.7.4) (3.2.0)

futures requires Python '>=2.6, <3' but the running Python is 3.7.2
```

Anyone who can help with this?

**Comment by RNogales94** [comment]
To install polyglot in Windows using a Python 3.6 or Python 3.7 you will need a wheel for two dependencies:

You need to download them and then install them with pip from your local machine.

Here you will found many unofficial python builds:
https://www.lfd.uci.edu/~gohlke/pythonlibs/

- install [PyICU.whl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#PyICU)
- install [PyCLD2.whl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycld2)

In both cases you will need be able to choose the right version of the build for your windows version and your python version.

It's easy, for example for [PyICU](https://www.lfd.uci.edu/~gohlke/pythonlibs/#PyICU):

> PyICU wraps the ICU (International Components for Unicode) library.
> 
>     PyICU‑2.3.1‑cp27‑cp27m‑win32.whl
>     PyICU‑2.3.1‑cp27‑cp27m‑win_amd64.whl
>     PyICU‑2.3.1‑cp35‑cp35m‑win32.whl
>     PyICU‑2.3.1‑cp35‑cp35m‑win_amd64.whl
>     PyICU‑2.3.1‑cp36‑cp36m‑win32.whl
>     PyICU‑2.3.1‑cp36‑cp36m‑win_amd64.whl
>     PyICU‑2.3.1‑cp37‑cp37m‑win32.whl
>     PyICU‑2.3.1‑cp37‑cp37m‑win_amd64.whl

the 27 means Python 2.7 and the 36 Python 3.6...
If you have 64 bits python and windows then choose the amd64 otherwhise the win32 version.

Once you have download them you will need to install it using pip in your python environment:

In my case:
`python -m pip install C:\Users\Administrator\Downloads\pycld2-0.31-cp37-cp37m-win_amd64.whl
 python -m pip install C:\Users\Administrator\Downloads\PyICU-2.3.1-cp37-cp37m-win_amd64.whl

pip install git+https://github.com/aboSamoor/polyglot@master
`

**Comment by AnuragHalder** [comment]
> For Windows 8
> 
> After installing PyICU.whl and PyCLD2.whl, I tried
> `pip install -U git+https://github.com/aboSamoor/polyglot.git@master`
> 
> I get an error saying 'Futures python package requires python >= 2.6' and I'm using Python 3.7
> 
> ```
> +https://github.com/aboSamoor/polyglot.git@master
> Collecting git+https://github.com/aboSamoor/polyglot.git@master
>   Cloning https://github.com/aboSamoor/polyglot.git (to revision master) to c:\u
> sers\user\appdata\local\temp\pip-req-build-v301wqo4
> Requirement already satisfied, skipping upgrade: wheel>=0.23.0 in c:\users\user\
> appdata\local\programs\python\python37\lib\site-packages\wheel-0.33.0-py3.7.egg
> (from polyglot==16.7.4) (0.33.0)
> Requirement already satisfied, skipping upgrade: PyICU>=1.8 in c:\users\user\app
> data\local\programs\python\python37\lib\site-packages (from polyglot==16.7.4) (2
> .2)
> Requirement already satisfied, skipping upgrade: futures>=2.1.6 in c:\users\user
> \appdata\local\programs\python\python37\lib\site-packages\futures-3.2.0-py3.7.eg
> g (from polyglot==16.7.4) (3.2.0)
> 
> futures requires Python '>=2.6, <3' but the running Python is 3.7.2
> ```
> 
> However, I managed to install polyglot by downloading the package and calling `python setup.py install`
> 
> And I can see it being added under my project interpreter, but it's unable to import the module
> 
> `ModuleNotFoundError: No module named 'polyglot.transliteration'; 'polyglot' is not a package`
> 
> Anyone who can help with this?

Did you run: `python setup.py install` once you are in the cloned folder
