### ISSUE TITLE
Docs: unescaped backslashes not showing in "parsed-literal" 

### ISSUE THREAD

**Issue by staii** [aboSamoor/polyglot#14]
For example, in READM.rst, under "Named Entity Recognition", the result should include a visible backslash at "\xfd", but this is parsed by the `parsed-literal` body element.

While it could be possible to escape the backslash and have it shown correctly when rendered, this would be confusing to someone reading the document in raw format.

Consider using the `code` body element instead, or showing results as comments in the code preceding them.

**Comment by alantian** [comment]
Thanks for pointing it out. It has been reflected in https://github.com/aboSamoor/polyglot/commit/a423198696e81219b3f8257b988fe3d538e05e11
