### ISSUE TITLE
Available packages to download

### ISSUE THREAD

**Issue by valeriocos** [aboSamoor/polyglot#15]
I'm trying to list all the available packages using ```downloader.list(show_packages=False)```
however only two are retrieved (```LANG:zhc, TASK:tsne2/zhc```).
I've also tried to manually set the URL that points to the package index file, but the default link provided in the documentation (```http://nltk.googlecode.com/svn/trunk/polyglot_data/index.xml```) does not exist anymore.

**Comment by aboSamoor** [comment]
Polyglot does not use the nltk xml file. This part of documentation should
be changed. zhc is character based embeddings and I do not think we have
tnse2 for that.

On Fri, Jul 31, 2015 at 8:13 AM, valerio <notifications@github.com> wrote:

> I'm trying to list all the available packages using
> downloader.list(show_packages=False)
> however only two are retrieved (LANG:zhc, TASK:tsne2/zhc).
> I've also tried to manually set the URL that points to the package index
> file, but the default link provided in the documentation (
> http://nltk.googlecode.com/svn/trunk/polyglot_data/index.xml) does not
> exist anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aboSamoor/polyglot/issues/15>.
>



-- 
Rami Al-Rfou
https://bit.ly/rmyeid
