### ISSUE TITLE
Analogy task with polyglot

### ISSUE THREAD

**Issue by tareksakakini** [aboSamoor/polyglot#17]
I can't seem to find a way, using polyglot, to test word analogies like having v["queen"] closest to v["king"] - v["man"] + v["woman"]. Basically I'd like to find neighbors of a linear combination of vectors of words instead of a single word vector.

**Comment by aboSamoor** [comment]
https://github.com/aboSamoor/polyglot/blob/1bb1dc1/polyglot/mapping/embeddings.py#L104

The nearest nighbor function takes a word, but you can use almost code to write a new function that takes a point that just the results of v["king"] - v["man"] + v["woman"]

```python
    point = v["king"] - v["man"] + v["woman"]
    diff = self.vectors - point
    distances = np.linalg.norm(diff, axis=1)
    top_ids = distances.argsort()[1:top_k+1]
    return [self.vocabulary.id_word[i] for i in top_ids]

```

**Comment by tareksakakini** [comment]
Got it. Thanks a lot!
