### ISSUE TITLE
Unable to download models, 401 unauthorized error

### ISSUE THREAD

**Issue by andrely** [aboSamoor/polyglot#18]
When I try to download any model I get a 401 unauthorized error.

(default)vagrant@vagrant-ubuntu-trusty-64:~$ !polyglot download morph2.en
polyglot download embeddings2.en download morph2.en
[polyglot_data] Downloading package embeddings2.en to
[polyglot_data]     /home/vagrant/polyglot_data...
[polyglot_data] Error downloading u'embeddings2.en' from
[polyglot_data]     <https://www.googleapis.com/download/storage/v1/b
[polyglot_data]     /polyglot-models/o/embeddings2%2Fen%2Fembeddings_p
[polyglot_data]     kl.tar.bz2?generation=1406139163483000&alt=media>:
[polyglot_data]     HTTP Error 401: Unauthorized

**Comment by aboSamoor** [comment]
Hi Andrely,

Hosting the models is becoming more expensive every month. Usually, once you download the models you do not have to download them again. Apparently, users are downloading the same models so many times.

I am looking into uploading the models to a different hosting service.

**Comment by aboSamoor** [comment]
I am currently working on a fix, I will update the issue tracker once the solution is available in the next couple of days.

**Comment by andrely** [comment]
Ayup, I totally understand this :(

It's the first time I'm looking at your library so I'll have to plead not guilty to abusing your generosity.

You probably already know this, but for lazy bums like me using stuff like ansible, vagrant and fabric just redownloading everything when something changes in the dev or production deployments is just too easy I guess.

Are there any alternative ways to access the models if you are not able to put them back online soon?


Kind regards

André Lynum

**Comment by alantian** [comment]
Please check out #19 where we tried to solve is issue.

Please then comment on whether it works.
