### ISSUE TITLE
icu module not found

### ISSUE THREAD

**Issue by dreygur** [aboSamoor/polyglot#209]
The module 'icu' isn't found in pypi nor any information installing it provided.
Please fix the issue.

**Comment by b-long** [comment]
Seems like a recurring issue for this package, see also:

- https://github.com/aboSamoor/polyglot/issues/192
- https://github.com/aboSamoor/polyglot/issues/152

**Comment by matalab** [comment]
For Windows installation, solution is here:
https://stackoverflow.com/questions/56966629/i-had-issue-with-installing-icu-in-python-3-5-windows-10
