### ISSUE TITLE
Data and NLP Models

### ISSUE THREAD

**Issue by tgalery** [aboSamoor/polyglot#22]
Thanks for the awesome lib @aboSamoor . I'm taking a look at your `load` module and it seems that it provides the ability to unpickle data into different objects depending of the nlp task in question. I was wondering if there is any documentation on:

- how these different models were  created (data sources, etc... )
- whether the original data sources are available  (is some format)
- benchmarks of the performance of different models
- whether we can re-train some models in case we need.

Thanks again and sorry if github is not the right place to put these questions

**Comment by aboSamoor** [comment]
I am glad you found the work to be useful. These models are result of the research I conducted in my PhD. You can take a look into my projects page to see details and datasets (https://sites.google.com/site/rmyeid/projects). In the documentation (polyglot-nlp.com), you can notice that I mentioned under each functionality the technical paper that details are described in. The papers include details like performance of models and so on. Most of these models were trained using code that relies on Theano (deep learning library).

Let me know if you have further questions.

**Comment by tgalery** [comment]
Thanks @aboSamoor I read the ner paper and will read the other projects too. I was really interested in how you guys parse the data in wikipedia to produce the corpus you feed to generate the models. I say this, because very similar tricks, like the exact surface form matching, is used to produce stats for entity linking (I'm a member of the dbpedia spotlight community). So if we could have a tooling that could be used to generate data for both the tasks that polyglot does but also something else, it would be great. Well, in addition to this comment, I do have a few questions:

- in your paper, you mention that you'd consider only links that have a freebase category, why not consider links that might lack a freebase category but might have a dbpedia one ? (you might get better coverage)
- for the exact surface form match step, the first sentence of the wikipedia page contains wikimedia markup that indicate other ways in which an entity might be referred to, for instance, the Brazilian president Luis Inácio Da silva is often referred to as 'Lula' , but that appears in bold in the first page, so capturing that and replacing matches for 'lula' in the article on the president could improve results too. Have you considered using this kind of method ?
I was wondering whether you could consider outputing the 'Non-entity' tag as well. This might be able to solve the mention detection problem of entity linking for entities that do not fall under the standard categories (say, consumer products) and be used in a further entity disambiguation task.
Do the embeddings allow you to do something like the word2vec query 'king -man + woman = queen' (like gensim does)?

**Comment by aboSamoor** [comment]
Hi,

- At the time freebase had a clean API and MQL editor that we managed to understand. There is no reason not to use dbpedia. Especially, that freebase is out of service.

- In any article X, if Barack Obama was linked to his own page (Y), words as Barack or Obama will be also considered Named Entity within that specific page (X). This rule applies to all words except frequent one. So if an entity like University of Harvard appeared to be linked, we will apply our expansion of labels to University mentions and Harvard mentions but not 'of'. 

- Detecting entities out of the three supported categories in beyond the scope of our work.

- It depends on which type of embeddings you are using. Polyglot models has two different embeddings: 1) Word2Vec embeddings which has better analogy support. 2) Collobert and Weston - like embeddings which do not support analogies as well.
