### ISSUE TITLE
Model download fails (HTTP 403)

### ISSUE THREAD

**Issue by Murodese** [aboSamoor/polyglot#24]
This may be temporary or not, but the model downloads are failing currently:

```
[polyglot_data] Downloading collection 'TASK:embeddings2'
[polyglot_data]    |
[polyglot_data]    | Downloading package embeddings2.fy to
[polyglot_data]    |     /home/ubuntu/polyglot_data...
[polyglot_data]    | Error downloading 'embeddings2.fy' from
[polyglot_data]    |     <https://www.googleapis.com/download/storage/
[polyglot_data]    |     v1/b/polyglot-models/o/embeddings2%2Ffy%2Femb
[polyglot_data]    |     eddings_pkl.tar.bz2?generation=14061390326200
[polyglot_data]    |     00&alt=media>:   HTTP Error 401: Unauthorized
```

**Comment by AlexSnet** [comment]
Yes,  this really happens. Where we can find a mirror? How about to create a mirror like NLTK in github pages?

**Comment by aboSamoor** [comment]
I recently merged a PR that changes the hosting mirror
https://github.com/aboSamoor/polyglot/commit/cffb0e71ac62c7f9966016964a60e96f9467d051

please updated your software to the new version. I will release new pypi polyglot package soon.

**Comment by AlexSnet** [comment]
Ok, this works. Thx, @aboSamoor ;)
