### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by apongos** [aboSamoor/polyglot#241]
After 
```
pip install polyglot
```

I try to run 

```
from polyglot.text import Text, Word

x ='word'
Word(x, language='en').morphemes
```

and I get this error:
urllib.error.HTTPError: HTTP Error 403: Forbidden

TLDR
pip install failed and downloaded polyglot-15.10.3 from cache instead of polyglot 16.7.4
This cached version of polyglot pointed to this url:
https://whoisbigger.com/polyglot/index.json

The url should have been
http://polyglot.cs.stonybrook.edu/~polyglot/

Downloading the tar and running python setup.py install resolved my issue :)

**Comment by apongos** [comment]
Perhaps related, I also tried downloading english embeddings 

```
from polyglot.downloader import downloader
downloader.download("embeddings2.en")
```

 And get this error
[polyglot_data] Error loading embeddings2.en: HTTP Error 403:
[polyglot_data]     Forbidden

**Comment by apongos** [comment]
I'm looking at one of my working installations of polyglot and the download url is instead

http://polyglot.cs.stonybrook.edu/~polyglot/

I think someone replaced the url with a bad one?

**Comment by MarcelinoV** [comment]
@apongos Where does the http://polyglot.cs.stonybrook.edu/~polyglot/ link go? In the downloader file?

**Comment by rp2839** [comment]
It can be changed in the Downloader.py file. Around line 364 - at least in the version I installed which was 15.10.3

**Comment by jlmeunier** [comment]
Hello,
in version 16.7.4, the URL is correct in file polyglot/downloader.py (line 364 indeed)
But I'm getting the  HTTP Error 403 
Also in a browser BTW.
Thanks for any help
JL
