### ISSUE TITLE
Where to get all models as one archive?

### ISSUE THREAD

**Issue by hodzanassredin** [aboSamoor/polyglot#26]
I\m trying to download models from http://whoisbigger.com/polyglot. But unfortunately it shows 0 bps after some time. Could you give me a link to an alternative donwload?

**Comment by aboSamoor** [comment]
Try:
http://whoisbigger.com/polyglot/index.json

This index include all the files.

If you do not want to deal with the file, use polyglot download subcommand

**Comment by hodzanassredin** [comment]
Downloader from pypi uses google and doesn't work at all. Latest version from github shows that everything is downloaded(downloader.download("embeddings2.ru")), but during execution, for example some POS or NER tagging code, shows errors like unexpected EOF o compressed file. Seems that problem in that mirror http://whoisbigger.com/polyglot. When I tries to download files manually like embeddings2 ru it just freezes and shows download speed 0 bps. One more problem that by default downloader downloads everything into / directory so after installation I have to go to configuration and setud different location. It is better to use some /usr/local/ folder..

**Comment by aboSamoor** [comment]
Yes, pypi package uses the old mirror, you need to use the updated github code.

Embeddings are not enough to run POS and NER, you need to download POS and NER models for Russian. The new mirror works, you just did not download all the necessary models.

**Comment by hodzanassredin** [comment]
Ok I'll try. But is there any command to download everything? Or everything for a single language?

**Comment by hodzanassredin** [comment]
Or download on demand during code execution?

**Comment by aboSamoor** [comment]
Look at the documentation for commands to download all models or all models
for a specific language.

**Comment by hodzanassredin** [comment]
My miss. Thanks I found this section. It is hidden in words. Probably better idea is to highjlight it somehow.

**Comment by hodzanassredin** [comment]
And yes seems that pypi version has correct download directory inside home dir. Probably one more my miss during installation of latest version. Thanks for your work and support.

**Comment by hodzanassredin** [comment]
Started download for LANG:ru half an hour ago and it is still downloading first file.

**Comment by aboSamoor** [comment]
If it is downloading, then it is ok. If you do not see progress in the
download, then you should contact skiena@cs.stonybrook.edu.

The new mirror could be slower than the previous one (Google) but it is for
free :).

**Comment by hodzanassredin** [comment]
OK I'll leave it for night. Hope it will do the thing.

**Comment by aboSamoor** [comment]
try to start in parallel another download and see if the other is faster,
maybe this one is pathologically slow.

**Comment by hodzanassredin** [comment]
d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d  

Download which package (l=list; x=cancel)?
  Identifier> LANG:ru
  Downloading collection u'LANG:ru'
     | 
     | Downloading package counts2.ru to /home/hodza/polyglot_data...
     | Downloading package sgns2.ru to /home/hodza/polyglot_data...
     | Downloading package transliteration2.ru to
     |     /home/hodza/polyglot_data...
     | Downloading package embeddings2.ru to
     |     /home/hodza/polyglot_data...
     | Downloading package ner2.ru to /home/hodza/polyglot_data...
     | Downloading package tsne2.ru to /home/hodza/polyglot_data...
     | Downloading package sentiment2.ru to
     |     /home/hodza/polyglot_data...
     | Downloading package morph2.ru to /home/hodza/polyglot_data...
     | 
   Done downloading collection LANG:ru

---------------------------------------------------------------------------
  d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q   
hodza@hodza-aspire:~$ polyglot --lang ru ner 
Traceback (most recent call last):
  File "/usr/local/bin/polyglot", line 9, in <module>
    load_entry_point('polyglot==15.5.2', 'console_scripts', 'polyglot')()
  File "/usr/local/lib/python2.7/dist-packages/polyglot/__main__.py", line 280, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/polyglot/__main__.py", line 86, in ner_chunk
    chunker = NEChunker(lang=args.lang)
  File "/usr/local/lib/python2.7/dist-packages/polyglot/tag/base.py", line 99, in __init__
    super(NEChunker, self).__init__(lang=lang)
  File "/usr/local/lib/python2.7/dist-packages/polyglot/tag/base.py", line 40, in __init__
    self.predictor = self._load_network()
  File "/usr/local/lib/python2.7/dist-packages/polyglot/tag/base.py", line 104, in _load_network
    self.embeddings = load_embeddings(self.lang, type='cw')
  File "/usr/local/lib/python2.7/dist-packages/polyglot/decorators.py", line 30, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/polyglot/load.py", line 65, in load_embeddings
    e = Embedding.load(p)
  File "/usr/local/lib/python2.7/dist-packages/polyglot/mapping/embeddings.py", line 254, in load
    content = _open(fname).read()
  File "/usr/lib/python2.7/tarfile.py", line 823, in read
    buf += self.fileobj.read()
  File "/usr/lib/python2.7/tarfile.py", line 743, in read
    return self.readnormal(size)
  File "/usr/lib/python2.7/tarfile.py", line 752, in readnormal
    return self.fileobj.read(size)
EOFError: compressed file ended before the logical end-of-stream was detected

**Comment by aboSamoor** [comment]
Make sure that you cleaned your models directory from previously downloaded
models. If you start from a fresh clean state, you should not get this
error.

**Comment by hodzanassredin** [comment]
No. Reason for that error is a corrupted file.

hodza@py-trainer:~$ tar -vxjf /home/hodza/polyglot_data/embeddings2/ru/embeddings_pkl.tar.bz2 > /dev/null

bzip2: Compressed file ends unexpectedly;
        perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
        Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
hodza@py-trainer:~$
