### ISSUE TITLE
Seems that docs for transliteration has partially wrong content

### ISSUE THREAD

**Issue by dchaplinsky** [aboSamoor/polyglot#29]
http://polyglot.readthedocs.org/en/latest/Transliteration.html

Everything below 
Downloading Necessary Models
belongs to POS example

**Comment by alantian** [comment]
Thanks for pointing it out. It has been reflected in https://github.com/aboSamoor/polyglot/commit/f27e67ae27055ca4e9e65cd03717f841d36000fe
