### ISSUE TITLE
installation faild 

### ISSUE THREAD

**Issue by zainjaradat** [aboSamoor/polyglot#30]
I want to use your tool polyglotner,But it appears to me this error and tried to repair it frequently but I could not, I need this tool a lot.
can you help me ?please?
![error](https://cloud.githubusercontent.com/assets/15122152/10542900/16c522f0-7424-11e5-80d3-51dbf9c55a57.png)
Thank you very much

**Comment by aboSamoor** [comment]
I think you need to run

sudo apt-get install python-dev python-setuptools

**Comment by zainjaradat** [comment]
All requirements exist and the latest versions ,But I have a 32-bit Ubuntu and python 3.4.
 this is my file for libpython3.4-dev

![12](https://cloud.githubusercontent.com/assets/15122152/10558597/c836ce7a-74de-11e5-82bc-fcd529ee8d3a.png)

and the error  
![13](https://cloud.githubusercontent.com/assets/15122152/10558603/e2e56b78-74de-11e5-9b81-97e77cc8c487.png)

**Comment by fabiofumarola** [comment]
why you don't use [Miniconda](http://conda.pydata.org/miniconda.html). You can create a virtual env with different python version.

**Comment by pcbje** [comment]
It's the "-m64" argument in https://github.com/aboSamoor/pycld2/blob/master/setup.py that is causing the "x86_64-linux-gnu/python2.7/pyconfig.h: No such file or directory" error on 32bit systems.

**Comment by zainjaradat** [comment]
Hank you .. i solved it a long time ago..

**Comment by neopedro** [comment]
@zainjaradat How did you solved? I'm having the same problem.

**Comment by zainjaradat** [comment]
I replaced the OS from 64 bit to 32bit.
