### ISSUE TITLE
build new ner-model

### ISSUE THREAD

**Issue by HaniehP** [aboSamoor/polyglot#33]
Hi.
Is there anyway to build a new ner-model based on a my dataset?

**Comment by aboSamoor** [comment]
Consider using https://github.com/attardi/deepnl for training new models.

**Comment by tgalery** [comment]
In your paper, you mention that you generate some datasets out of freebase. Did you use a specific repo to do that ? If so would you be able to share it with us (it would be awesome to have this info on the readme).

**Comment by aboSamoor** [comment]
Check my personal website for the datasets.
