### ISSUE TITLE
 tsne2, sgns2

### ISSUE THREAD

**Issue by Ulitochka** [aboSamoor/polyglot#39]
Hello, thanks for your work.

What kind of data tsne2, sgns2?

**Comment by aboSamoor** [comment]
@Ulitochka 

- **tsne2**: is 2 dimensional embeddings created by [tsne](https://lvdmaaten.github.io/tsne/) for the most frequent 5k words in each language for the purposes of visualization.

- **sgns2**: Skip gram word embeddings of that specific language. You can access them using [polyglot library of embeddings](http://polyglot.readthedocs.org/en/latest/Embeddings.html).
