### ISSUE TITLE
Tokenization malfunction after strange character

### ISSUE THREAD

**Issue by remibolcom** [aboSamoor/polyglot#41]
>>> Text("Edge cases " + chr(917631) + " can be annoying.").words
WordList(['Edge', 'cases', '\U000e007f', 'c', 'an', 'b', 'e', 'a', 'nnoying.'])

**Comment by alantian** [comment]
For some of the i18n functionality, Polyglot is using PyICU (https://github.com/ovalhub/pyicu) which is merely a Python wrapper for ICU (http://site.icu-project.org/). Some debugging shows that the mistake using the provided example happens _inside_ ICU which is beyond the reach of Polyglot, thus currently there is little we can do.
