### ISSUE TITLE
Unexpected POS result

### ISSUE THREAD

**Issue by natsheh** [aboSamoor/polyglot#42]
Hi Rami @aboSamoor,

In the following example, I expected to have 'VERB' pos_tag for the word 'restate', however, I got 'NUM':

blob ="""restate (words) from one language into another language."""
text = Text(blob)
text.pos_tags
text.words[0].pos_tag
>> u'NUM'

**Comment by alantian** [comment]
Hi @natsheh ,
It seems that this is a mistake in model rather than a bug in code. Will investigate the model later.

**Comment by natsheh** [comment]
Hi @alantian and @aboSamoor 
Just a suggestion; May be it would be safer to tag such 'Unknown words' with 'X: other' rather than 'NUM'. I saw few of these cases in which are tagged with 'NUM'.
Thanks
