### ISSUE TITLE
Force Language

### ISSUE THREAD

**Issue by brunoalano** [aboSamoor/polyglot#44]
Has anyway to force to Polyglot use a language? Sometimes when you run the NER, and the pharse have a foreign language entities (eg: "Albert Einstein"), it's classified wrong, for that example says that is: "de" (language code).

Have anyway to force a specific language?

The only way I've found it's to create custom method and overwrite the `def ne_chunker(self):` to accept params  (language_code) and then change the `def entities(self)` to accept the language code too.

```
def extract(self, pharse, language='pt'):
    # Transform pharse into `polyglot.text.Text`
    text = Text(pharse)

    # Create a named entitiy chunker
    ne_chunker = get_ner_tagger(lang=language)

    # Extract Entities
    start = 0
    end = 0
    prev_tag = u'O'
    chunks = []
    for i, (w, tag) in enumerate(ne_chunker.annotate(text.words)):
      if tag != prev_tag:
        if prev_tag == u'O':
          start = i
        else:
          chunks.append(Chunk(text.words[start: i], start, i, tag=prev_tag,
                              parent=text))
        prev_tag = tag
    if tag != u'O':
      chunks.append(Chunk(text.words[start: i+1], start, i+1, tag=tag,
                          parent=text))
    return chunks
```

**Comment by aboSamoor** [comment]
Did you try to set text.__lang so you prevent automatic detection of language?

**Comment by brunoalano** [comment]
@aboSamoor Didn't work. I've set the `text.__lang = 'pt'`. But I've found that I should define the `text.language.code` instead, but it's not possible to change it (read-only attribute).

**Comment by hodaking** [comment]
I don't know if it can help someone, but this solution works for me:
text.language = 'fr'

In your case: 
def extract(self, pharse, language='pt'):
    # Transform pharse into `polyglot.text.Text`
    text = Text(pharse)
    **text.language = 'pt'**
    ....
