### ISSUE TITLE
How to train new SRL model ? 

### ISSUE THREAD

**Issue by GraphGrail** [aboSamoor/polyglot#47]
Hi aboSamoor, i want to create Semantic Role Labeling model (non english).
Maybe this is offtopic for Polyglot, but you advice to use deepnl in other issue answer, so i would like to ask: how to  train new SRL model from raw text data?

Currently i try to use https://github.com/attardi/deepnl  and  https://github.com/erickrf/nlpnet  (both hard to implement due to unclear steps and data formats, asked in their Github pages but no clear solution provided). I want to use your pretrained wordembedings  from https://sites.google.com/site/rmyeid/projects/polyglot   to create SRL model.

What will you advice to solve this task?

**Comment by alantian** [comment]
Hi, @GraphGrail ,
To use the pre-trained word embeddings from Polyglot in your project, you can download and load it using Polyglot's Embedding class. The following examples assume that you have installed Polyglot as mentioned in https://polyglot.readthedocs.org/en/latest/Installation.html

Taking English (whose language code is `en`) as example, to download you may use the following Bash commands:
```bash
lang='en'
polyglot download embeddings2.${lang}
```

And to use it in your project, you may use the following Python snip:
```python
from os import path

from polyglot.mapping import Embedding

lang = 'en'
home = path.expanduser('~')
emb = Embedding.load(path.join(home, 'polyglot_data/embeddings2/%s/embeddings_pkl.tar.bz2' % lang))
words = emb.words
vectors = emb.vectors
```
And now you can play with `words`, which is a list of strings representing the vocabulary, and `vectors`, which is a 2-d NumPy array whose i-th row (`vectors[i]`) is the word embedding for the i-th word in `words`.
