### ISSUE TITLE
outdated model for 15.04.19?

### ISSUE THREAD

**Issue by geovedi** [aboSamoor/polyglot#5]
Hi, 

I just upgraded to polyglot 15.04.19 and it seems the model needs to be updated too.

```python
In [1]: from polyglot.downloader import downloader

In [2]: downloader.download("embeddings2.en")
[polyglot_data] Downloading package embeddings2.en to
[polyglot_data]     /home/ubuntu/polyglot_data...
Out[2]: True

In [3]: downloader.download("pos2.en")
[polyglot_data] Downloading package pos2.en to
[polyglot_data]     /home/ubuntu/polyglot_data...
Out[3]: True

In [4]: blob = """We will meet at eight o'clock on Thursday morning."""

In [5]: from polyglot.text import Text

In [6]: text = Text(blob)

In [7]: text.pos_tags
Out[7]:
[(u'We', u'INTJ'),
 (u'will', u'NOUN'),
 (u'meet', u'NOUN'),
 (u'at', u'ADP'),
 (u'eight', u'DET'),
 (u"o'clock", u'PART'),
 (u'on', u'ADP'),
 (u'Thursday', u'PART'),
 (u'morning', u'PART'),
 (u'.', u'ADV')]
```

Also you might want to update [this](https://github.com/aboSamoor/polyglot/blob/master/polyglot/__init__.py#L5) too.

**Comment by aboSamoor** [comment]
I am looking into it.

**Comment by aboSamoor** [comment]
Apparently, the new models did not overwrite the old models in google cloud storage because of naming differences.
Issue is fixed, let me know if it is still persistence.

Keep in mind that you need to delete your downloaded models.

**Comment by geovedi** [comment]
Excellent! Just re-downloaded all models. It's working again except for `transliteration` as I got unauthorised error when downloading the models.

```python
[polyglot_data] Downloading collection u'TASK:transliteration2'
[polyglot_data]    |
[polyglot_data]    | Downloading package transliteration2.nn to
[polyglot_data]    |     /home/ubuntu/polyglot_data...
[polyglot_data]    | Error downloading u'transliteration2.nn' from
[polyglot_data]    |     <https://www.googleapis.com/download/storage/
[polyglot_data]    |     v1/b/polyglot-models/o/transliteration2%2Fnn%
[polyglot_data]    |     2Ftransliteration.nn.tar.bz2?generation=14261
[polyglot_data]    |     02539267000&alt=media>:   HTTP Error 401:
[polyglot_data]    |     Unauthorized
Error installing package. Retry? [n/y/e]
```

**Comment by aboSamoor** [comment]
There was no read permission on these models.
I fixed it, sorry for the annoyance.

**Comment by BeenKimAI2** [comment]
Hi AboSamoor, 

I am getting a similar unauthorized error when I try to download morph2.en, and wondering if this is a similar issue. Thanks!

!polyglot download morph2.en
polyglot download morph2.en download morph2.en
[polyglot_data] Downloading package morph2.en to
[polyglot_data]     /Users/beenk/polyglot_data...
[polyglot_data] Error downloading u'morph2.en' from
[polyglot_data]     <https://www.googleapis.com/download/storage/v1/b
[polyglot_data]     /polyglot-models/o/morph2%2Fen%2Fen.morph.tar.bz2?
[polyglot_data]     generation=1425937760519000&alt=media>:   HTTP
[polyglot_data]     Error 401: Unauthorized
Error installing package. Retry? [n/y/e]

**Comment by aboSamoor** [comment]
Hi All,
We had to change the web hosting of the models because google cloud storage is expensive given the popularity of the package.

Can you please test PR #19 that changes the hosting solution? If it works for you, I will merge the change and republish the package :).

**Comment by BeenKimAI2** [comment]
This worked for me, Thanks!
