### ISSUE TITLE
Package data downloaded to / when superuser

### ISSUE THREAD

**Issue by pudo** [aboSamoor/polyglot#54]
When deploying polyglot to a docker container ubuntu environment (thus running as root inside the container), the downloader simply drops the resources into ``/`` -- looks like there might be a bug in how the ``package_data`` path is determined for a superuser. 

I was also wondering if it might make sense to consider a ``$POLYGLOT_PACKAGE_DATA`` environment variable when determining the path?

p.s. thanks for this amazing library! It's giving me great results and was much needed.

**Comment by aboSamoor** [comment]
Feel free to send me a PR to fix the issue.

**Comment by mekarpeles** [comment]
+1
