### ISSUE TITLE
New release on pypi

### ISSUE THREAD

**Issue by MerlijnWajer** [aboSamoor/polyglot#56]
Please consider doing a new release on pypi. Transliteration is broken in the current version, and it was fixed by my commit: https://github.com/aboSamoor/polyglot/commit/600514a1ebfd874a53360ea8cfe21756244e6995

I'm using polyglot in a project and it's not nice to have to get or build development versions manually.

It could also be a simple minor version 'bugfix' release.

**Comment by amirothman** [comment]
Is it not the same as pip from github master branch? I am asking because I'm still having problems with transliteration where the source language is not English.

**Comment by MerlijnWajer** [comment]
https://pypi.python.org/pypi/polyglot

Uploaded on: 2015-10-03

My commit doesn't predate that date. I'm confident that pypi at least doesn't have the correct version. If you still have trouble with transliteration with the HEAD of the github master branch, you may want to file a separate issue.

**Comment by mekarpeles** [comment]
+1 @amirothman @aboSamoor please push a 2016 v. w/ the latest code to pypi

**Comment by aboSamoor** [comment]
New release is uploaded to pypi
