### ISSUE TITLE
Transliterate into English

### ISSUE THREAD

**Issue by amirothman** [aboSamoor/polyglot#57]
Hi,

firstly, thanks for this great software. I realized that in the code, that when the target language is English, it will not transliterate it and returns the original text. Does polyglot does not support transliterating into English or am I missing something?

regards,
Amir

**Comment by aboSamoor** [comment]
Please check the version of the software available on github.

**Comment by amirothman** [comment]
Hi,

I did use the software available from github. I installed the new version with the following command:

    pip install -U git+https://github.com/aboSamoor/polyglot@master

[Here](https://gist.github.com/amirothman/750614148d3e7a421310eb73128c0a8a) is a gist demonstrating what is happening.

But this behaviour is somehow expected because in the code [transliteration/base.py](https://github.com/aboSamoor/polyglot/blob/master/polyglot/transliteration/base.py#L33), the decoder would be set to '_dummy_coder', if the target language is 'en', which would return the original text as is.

Which I find a bit unclear to me why is it doing so. Any form of help would be greatly appreciated.

Thanks again for the reply.

regards,
amir

**Comment by alantian** [comment]
Hi, @amirothman 

### Regarding transliteration

Polyglot transliterates when the target languages is English. For example, when source language is Russian, it works like:
```python
>>> Text("Язы́к — сложная знаковая система, естественно или искусственно созданная и соотносящая понятийное содержание и типовое звучание (написание).").transliterate(target_language="en")

WordList(['', '', 'slojnaya', 'znakovaya', 'sistema', '', 'estestwenno', 'ili', 'iskusstwenno', 'sozdannaya', 'i', 'sootnoxiaszczaya', 'poniatiinoe', 'soderjanie', 'i', 'tipovoe', 'zvuchanie', '', 'napisanie', '', ''])
```

### Regarding your example

The model for transliterating Malay is learnt to producing identical transliteration, which can be possibly explained by the fact that Malay is written in ISO basic Latin alphabet. This means words are not changed after transliteration.
