### ISSUE TITLE
Downloader: Only Russian models available

### ISSUE THREAD

**Issue by maxnkern** [aboSamoor/polyglot#92]
When I use the list function in the Polyglot downloader, only the Russian language models are shown. I can't download any packages except the Russian ones listed.

I am running python 3.5 on windows 10. Can anyone help me?

`C:\Users\max.nkern>polyglot download
Polyglot Downloader
--------------------------------------------------------------------
d) Download  l) List  u) Update   c) Config  h) Help  q) Quit
--------------------------------------------------------------------
Downloader> l

Collections:
  [*] LANG:ru............. Russisch             packages and models
  [*] TASK:morph2/ru...... morph2/ru

([*] marks installed packages)`

**Comment by sabrinawilske** [comment]
I have the same problem (windows 7, Python 3.5).

downloader.supported_languages()
-->
['Russian']

downloader.supported_tasks(lang="en")
-->
LanguageNotSupported: Language LANG:en is not supported

print(downloader.supported_languages_table("sentiment", 3))
-->
ValueError: Package 'TASK:sentiment' not found in index
...
TaskNotSupported: Task TASK:sentiment is not supported

text = Text("The movie was really good.")
for w in text.words:
    print(w, w.polarity)
-->
ValueError: Package 'sentiment2.en' not found in index

**Comment by sabrinawilske** [comment]
It seems that this problem goes back to the path.sep problem for windows discussed in [https://github.com/aboSamoor/polyglot/issues/12](https://github.com/aboSamoor/polyglot/issues/12).
I replaced all `path.sep` with `"/"` in downloader.py and re-ran `python setup.py install` and now the list of supported languages is much longer.

**Comment by maxnkern** [comment]
Thank you very much! It now works for me as well
